version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: loyalty_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 
      POSTGRES_DB: loyalty_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loyalty_network

  backend:
    build:
      context: ./loyalty-backend
      dockerfile: Dockerfile
    container_name: loyalty_backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/loyalty_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./loyalty-backend:/app
    networks:
      - loyalty_network

  frontend:
    build:
      context: ./loyalty-frontend
      dockerfile: Dockerfile
    container_name: loyalty_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./loyalty-frontend:/app
      - /app/node_modules
    networks:
      - loyalty_network

volumes:
  pgdata:

networks:
  loyalty_network:
    driver: bridge
